// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB2kYQBgD7BsMm9icEKjznPIgb1DY8meI',
    appId: '1:691105051129:web:7da36dece6c9ac61a40d28',
    messagingSenderId: '691105051129',
    projectId: 'live-football-stats-ee0f2',
    authDomain: 'live-football-stats-ee0f2.firebaseapp.com',
    storageBucket: 'live-football-stats-ee0f2.appspot.com',
    measurementId: 'G-P0E86EWCQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxxxA1kUqTRx3of8xa6CG2kt-DbOVoOQ',
    appId: '1:691105051129:android:db8c15036e2dcd43a40d28',
    messagingSenderId: '691105051129',
    projectId: 'live-football-stats-ee0f2',
    storageBucket: 'live-football-stats-ee0f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEj_kCsioMdHBtkrRfWf8U6UVXNA6yhw',
    appId: '1:691105051129:ios:d1ba48817cca9213a40d28',
    messagingSenderId: '691105051129',
    projectId: 'live-football-stats-ee0f2',
    storageBucket: 'live-football-stats-ee0f2.appspot.com',
    androidClientId: '691105051129-dm69kuqeq365b5l9d309vqia95ht2tqc.apps.googleusercontent.com',
    iosClientId: '691105051129-sp6445b51qsdbm92cdeqcec52uffbg26.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveFootballStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEj_kCsioMdHBtkrRfWf8U6UVXNA6yhw',
    appId: '1:691105051129:ios:d1ba48817cca9213a40d28',
    messagingSenderId: '691105051129',
    projectId: 'live-football-stats-ee0f2',
    storageBucket: 'live-football-stats-ee0f2.appspot.com',
    androidClientId: '691105051129-dm69kuqeq365b5l9d309vqia95ht2tqc.apps.googleusercontent.com',
    iosClientId: '691105051129-sp6445b51qsdbm92cdeqcec52uffbg26.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveFootballStats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB2kYQBgD7BsMm9icEKjznPIgb1DY8meI',
    appId: '1:691105051129:web:59d4f0f3d88fed43a40d28',
    messagingSenderId: '691105051129',
    projectId: 'live-football-stats-ee0f2',
    authDomain: 'live-football-stats-ee0f2.firebaseapp.com',
    storageBucket: 'live-football-stats-ee0f2.appspot.com',
    measurementId: 'G-7TKB72LVYE',
  );
}
