# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

   # workflow_dispatch is an event that allows you to manually start a workflow from the GitHub UI. 
   # You can go to a repository's Actions page on GitHub and press a button to manually start this workflow
   # whenever you need it, instead of waiting for an automatic event like a push or pull_request.
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
      - name: build APK
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk



      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

  release: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Retrieve Release Version
      id: versionstep
      run: |
        VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
        echo "::set-output name=VERSION::$VERSION"
        
    - name: Upload the APK onto Github
      uses: subosito/release-action@v1
      with:
        artifacts: 'build/app/outputs/flutter-apk/*.apk'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.versionstep.outputs.VERSION }}

    
